### ISSUE TITLE
The section “Restricting access based on route groups” of the document “Routing” mentions `wrap-routes` but doesn’t mention where that comes from

### ISSUE THREAD

**Issue by aviflax** [kit-clj/kit-clj.github.io#54]
https://kit-clj.github.io/docs/routes.html#restricting_access_based_on_route_groups

**Comment by yogthos** [comment]
Thanks for the heads up, the `wrap-routes` approach was a carryover from Luminus docs. Since Kit uses Reitit for routing, this is no longer necessary as you can add middleware to routes directly in the route declaration as shown here https://cljdoc.org/d/metosin/reitit/0.7.0-alpha7/doc/ring/data-driven-middleware

I've updated the docs to reflect this.
